services:
  - type: web
    name: medical-dictionary-backend
    runtime: node
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000